version: '3'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    networks:
      - trabalhosd
    command: redis-server --appendonly yes
    restart: always
  app:
    build: .
    volumes:
      - .:/app
    networks:
      - trabalhosd
    ports:
      - "8000:8000"
    depends_on:
      - redis
  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - ~/mongors/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - trabalhosd
    expose:
      - 27017
    ports:
      - 27021:27017
    links:
      - mongo2
      - mongo3
    restart: always
    command: mongod --replSet dbrs
  mongo2:
    container_name: mongo2
    image: mongo:4.4
    volumes:
      - ~/mongors/data2:/data/db
    networks:
      - trabalhosd
    expose:
      - 27017
    ports:
      - 27022:27017
    restart: always
    command: mongod --replSet dbrs
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    volumes:
      - ~/mongors/data3:/data/db
    networks:
      - trabalhosd
    expose:
      - 27017
    ports:
      - 27023:27017
    restart: always
    command: mongod --replSet dbrs

networks:
  trabalhosd:
    driver: bridge