version: '3'

services:
  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - ./data:/data
    networks:
      - trabalhosd
    command: redis-server --appendonly yes
    restart: always
  app:
    build: .
    volumes:
      - .:/app
    networks:
      - trabalhosd
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongoinit
  mongo1:
    container_name: mongo1
    image: mongo:4.4
    volumes:
      - ~/mongors/data1:/data/db
      - ./rs-init.sh:/scripts/rs-init.sh
    networks:
      - trabalhosd
    expose:
      - 27017
    ports:
      - 27021:27017
    links:
      - mongo2
      - mongo3
    restart: always
    command: mongod --replSet dbrs
  mongo2:
    container_name: mongo2
    image: mongo:4.4
    volumes:
      - ~/mongors/data2:/data/db
    networks:
      - trabalhosd
    expose:
      - 27017
    ports:
      - 27022:27017
    restart: always
    command: mongod --replSet dbrs
  mongo3:
    container_name: mongo3
    image: mongo:4.4
    volumes:
      - ~/mongors/data3:/data/db
    networks:
      - trabalhosd
    expose:
      - 27017
    ports:
      - 27023:27017
    restart: always
    command: mongod --replSet dbrs
  mongoinit:
    image: mongo:4.4
    restart: "no"
    networks:
      - trabalhosd
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    command: >
      sleep 10 && mongo --host mongo1:27017 --eval 
      '
      config = {
      "_id" : "dbrs",
      "version" : 1,
      "members" : [
        {
          "_id": 1,
            "host": "mongo1:27017",
            "priority": 2
        },
        {
          "_id": 2,
            "host": "mongo2:27017",
            "priority": 1
        },
        {
          "_id": 3,
            "host": "mongo3:27017",
            "priority": 1
        }
      ]
      };
      rs.initiate(config);
      '  

networks:
  trabalhosd:
    driver: bridge